# Question 1

## Question 1.a

In [3]:
import numpy as np
import pandas as pd
MatrixA = np.array([[5,5,0,4],[1,1,5,0],[3,2,0,4],[5,3,0,5],[0,0,4,0]])
#print matrix A and rank(A)
print('A = \n',MatrixA)
print('Matrix A rank(A) = ',np.linalg.matrix_rank(MatrixA))

# calculate SVD
U, S , Vt = np.linalg.svd(MatrixA)
#print U,V^T,Sigma
print('U = \n', np.around(U,2))
print('V^T = \n', np.around(Vt,2))
print('Sigma = ', np.around(S,2))

A = 
 [[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]
Matrix A rank(A) =  4
U = 
 [[-0.65 -0.04 -0.71  0.23  0.15]
 [-0.11  0.78 -0.14 -0.24 -0.55]
 [-0.43 -0.06  0.51  0.63 -0.4 ]
 [-0.62 -0.07  0.41 -0.64  0.2 ]
 [-0.02  0.62  0.22  0.31  0.69]]
V^T = 
 [[-0.63 -0.49 -0.05 -0.6 ]
 [ 0.01  0.04  0.99 -0.12]
 [-0.05 -0.75  0.11  0.66]
 [-0.78  0.45  0.04  0.44]]
Sigma =  [12.32  6.42  1.92  0.53]


In [4]:
UF, SigmaF, VTF = np.linalg.svd(MatrixA)
#print U,V^T,Sigma
print('UF = \n', np.around(U,2))
print('VF^T = \n', np.around(Vt,2))
print('SigmaF = ', np.around(S,2))

UF = 
 [[-0.65 -0.04 -0.71  0.23  0.15]
 [-0.11  0.78 -0.14 -0.24 -0.55]
 [-0.43 -0.06  0.51  0.63 -0.4 ]
 [-0.62 -0.07  0.41 -0.64  0.2 ]
 [-0.02  0.62  0.22  0.31  0.69]]
VF^T = 
 [[-0.63 -0.49 -0.05 -0.6 ]
 [ 0.01  0.04  0.99 -0.12]
 [-0.05 -0.75  0.11  0.66]
 [-0.78  0.45  0.04  0.44]]
SigmaF =  [12.32  6.42  1.92  0.53]


## Question 1.b

In [78]:
import numpy as np
import pandas as pd
MatrixA = np.array([[5,5,0,4],[1,1,5,0],[3,2,0,4],[5,3,0,5],[0,0,4,0]])
#print matrix A and rank(A)
print('A = \n',MatrixA)
print('Matrix A rank(A) = ',np.linalg.matrix_rank(MatrixA))

# calculate SVD
U, S , Vt = np.linalg.svd(MatrixA, full_matrices= False)
Sigma_matrix = np.diag(S)

sigma_1_u_1 = Sigma_matrix[0,0] *  (- U[:,0])
sigma_2_u_2 = Sigma_matrix[1,1] *  (- U[:,1])
sigma_3_u_3 = Sigma_matrix[2,2] *  ( U[:,2])
sigma_4_u_4 = Sigma_matrix[3,3] *  ( U[:,3])

print('Av_1 = sigma_1_u_1 = \n',sigma_1_u_1)
print('Av_2 = sigma_2_u_2 = \n',sigma_2_u_2)
print('Av_3 = sigma_3_u_3 = \n',sigma_3_u_3)
print('Av_4 = sigma_4_u_4 = \n',sigma_4_u_4)

A = 
 [[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]
Matrix A rank(A) =  4
Av_1 = sigma_1_u_1 = 
 [8.0041243967 1.3730084285 5.2709034792 7.619552617  0.2021626828]
Av_2 = sigma_2_u_2 = 
 [ 0.2662929463 -5.0029498565  0.3872736847  0.4591731926 -3.9687149493]
Av_3 = sigma_3_u_3 = 
 [-1.35973748   -0.263037338   0.9791605386  0.7870913621  0.426961497 ]
Av_4 = sigma_4_u_4 = 
 [ 0.1191414861 -0.1270903136  0.329909451  -0.3347612341  0.1616656463]


## Question 1.c

See Assignment 4 pdf

# Question 2

## Question 2.a

In [86]:
import numpy as np
import pandas as pd
# Example usage
B = np.array([
    [3,1,3,1],
    [1,5,3,1],
    [3,3,6,3],
    [1,1,3,2]
])
B_egienvalues,B_eigenvectors = np.linalg.eigh(B)
print(B_egienvalues)
print(B_eigenvectors)

[ 0.103727926   1.5685288041  3.3634213784 10.9643218915]
[[ 0.3319950458  0.7697466936 -0.3973623923 -0.373326193 ]
 [ 0.1615782784  0.1365936504  0.8510690781 -0.4805372608]
 [-0.6085130034 -0.2180944068 -0.2554156082 -0.71896427  ]
 [ 0.702412752  -0.5841806502 -0.2292322417 -0.3358599011]]


In [87]:
import numpy as np
import pandas as pd

def QR_Algorithm(B, tol=1e-6, max_iter=10000):
    n = B.shape[0] # get B
    Q = np.eye(n) # get Q = I  the identity
    iter_count = 0 # xunhuancishu 
    
    while iter_count < max_iter: # set number of iteration 
        Q_temp, R = np.linalg.qr(B) # use qr factorization
        B = R @ Q_temp # update
        Q = Q @ Q_temp #update
        
        # Check for convergence
        off_diagonal = B - np.diag(np.diagonal(B)) 
        if np.linalg.norm(off_diagonal, 'fro') < tol:
            print("Convergence achieved after", iter_count, "iterations.")
            break
        
        iter_count += 1
        print("Current B matrix:\n", B)
        user_input = input("Continue (y/n)? ")
        if user_input.lower() == 'n':
            break
    
    return B, Q

# Example usage
B = np.array([
    [3,1,3,1],
    [1,5,3,1],
    [3,3,6,3],
    [1,1,3,2]
])
qreigenvalues, qreigenvectors = QR_Algorithm(B)
#np.set_printoptions(precision=3, suppress=True)
print("Approximate diagonal matrix of eigenvalues:\n", qreigenvalues)
print("Matrix of eigenvectors:\n", qreigenvectors)
#print approximate diagonal mattrix of eigenvalues
print(qreigenvalues[0,0],qreigenvalues[1,1],qreigenvalues[2,2],qreigenvalues[3,3])

Current B matrix:
 [[ 9.6           2.5728968071  1.7661016572 -0.0329690237]
 [ 2.5728968071  4.2585858586  0.1774998951 -0.0033135116]
 [ 1.7661016572  0.1774998951  2.0327184892 -0.0939491871]
 [-0.0329690237 -0.0033135116 -0.0939491871  0.1086956522]]
Current B matrix:
 [[10.872423945   0.797930561   0.2881783415  0.0003393079]
 [ 0.797930561   3.4150801547 -0.2112479947 -0.0002487283]
 [ 0.2881783415 -0.2112479947  1.6087482629  0.0054264483]
 [ 0.0003393079 -0.0002487283  0.0054264483  0.1037476374]]
Current B matrix:
 [[10.9568112617  0.2364336172  0.0417639696 -0.0000032274]
 [ 0.2364336172  3.3635487919 -0.1124236444  0.0000086877]
 [ 0.0417639696 -0.1124236444  1.5759119352 -0.0003536095]
 [-0.0000032274  0.0000086877 -0.0003536095  0.1037280111]]
Current B matrix:
 [[10.9636397062  0.0718435156  0.0059867988  0.0000000305]
 [ 0.0718435156  3.3625235807 -0.0531216077 -0.000000271 ]
 [ 0.0059867988 -0.0531216077  1.5701087866  0.0000233178]
 [ 0.0000000305 -0.000000271   0.000

In [88]:
print("QR_Algorithm B eigenvalues: \n",qreigenvalues[0,0],qreigenvalues[1,1],qreigenvalues[2,2],qreigenvalues[3,3])
print("numpy.linalg.eigh(B) B eigenvalues: \n",B_egienvalues[3],B_egienvalues[2],B_egienvalues[1],B_egienvalues[0])

QR_Algorithm B eigenvalues: 
 10.964315909149002 3.3633527179506095 1.5686034468629337 0.1037279260374569
numpy.linalg.eigh(B) B eigenvalues: 
 10.964321891452668 3.3634213783919993 1.568528804117882 0.10372792603744915


## Question 2.b

In [90]:
import numpy as np
import pandas as pd
C = np.array([
    [2,1,0,0],
    [2,3,1,1],
    [2,2,1,1],
    [1,2,2,5]
])
def QR_Algorithm(B, tol=1e-6, max_iter=10000):
    n = B.shape[0] # get B
    Q = np.eye(n) # get Q = I  the identity
    iter_count = 0 # xunhuancishu 
    
    while iter_count < max_iter: # set number of iteration 
        Q_temp, R = np.linalg.qr(B) # use qr factorization
        B = R @ Q_temp # update
        Q = Q @ Q_temp #update
        
        # Check for convergence
        off_diagonal = B - np.diag(np.diagonal(B)) 
        if np.linalg.norm(off_diagonal, 'fro') < tol:
            print("Convergence achieved after", iter_count, "iterations.")
            break
        
        iter_count += 1
        print("Current C matrix:\n", B)
        user_input = input("Continue (y/n)? ")
        if user_input.lower() == 'n':
            break
    
    return B, Q
Cqreigenvalues, Cqreigenvectors = QR_Algorithm(C)
#np.set_printoptions(precision=3, suppress=True)
print("Approximate diagonal matrix of eigenvalues:\n", Cqreigenvalues)
print("Matrix of eigenvectors:\n", Cqreigenvectors)

Current C matrix:
 [[ 5.7692307692  0.6863213971 -0.0792495687 -1.8208739259]
 [ 2.6329784507  2.3886639676  1.4562316506 -0.0792495687]
 [ 1.4481057548  1.6338778873  2.5344129555 -0.2121357046]
 [-0.266469355  -0.5187244495 -0.6987999679  0.3076923077]]
Current C matrix:
 [[ 6.8784029038 -0.7080925918  0.3827007158  1.5506481951]
 [ 1.4610843915  2.7859895206  0.5386829371 -1.314049756 ]
 [ 0.2873606234  0.7005152915  1.0216540872 -0.008449701 ]
 [ 0.013240829   0.0617516582  0.0457797235  0.3139534884]]
Current C matrix:
 [[ 6.8846506174 -1.4160355154  0.6521933631 -1.2376058259]
 [ 0.6386849815  2.9311460916 -0.1176680734  1.6282841345]
 [ 0.0359981544  0.2131763597  0.8517164492 -0.303014321 ]
 [-0.0006260723 -0.0069646491 -0.011789991   0.3324868418]]
Current C matrix:
 [[ 6.7829684269 -1.7213120263  0.7481940269  1.0765190489]
 [ 0.2816468754  3.0240006522 -0.3594021208 -1.7112625032]
 [ 0.0045107644  0.062544394   0.8626376357  0.4135034016]
 [ 0.0000299192  0.0007638653  0.004

In [83]:
C_eigenvalues, C_eigenvectors = np.linalg.eigh(C)
#np.set_printoptions(precision=3, suppress=True)
print(C_eigenvalues)
print(C_eigenvectors)

[-0.7757531586  0.4919212438  2.770175267   8.5136566478]
[[ 0.4748718367  0.6004319187 -0.5156023851 -0.3848797608]
 [ 0.1080179622 -0.7524943749 -0.3876256544 -0.5213738464]
 [-0.8553665074  0.2562644695 -0.1819982621 -0.4117684936]
 [ 0.1765700898  0.0869611898  0.7421436284 -0.6406899326]]


## Question 2.c

In [91]:
import numpy as np

def qr_algorithm_fixed_iterations(B, num_iterations):
    n = B.shape[0]
    Q = np.eye(n)
    for _ in range(num_iterations):
        Q_temp, R = np.linalg.qr(B)
        B = R @ Q_temp
        Q = Q @ Q_temp
    return B, Q


A = np.array([
    [5, 5, 0, 4],
    [1, 1, 5, 0],
    [3, 2, 0, 4],
    [5, 3, 0, 5],
    [0, 0, 4, 0]
])
zeros_left = np.zeros((5,5))
zeros_right = np.zeros((4,4))

S = np.block([
    [zeros_left, A],
    [A.T, zeros_right]
])


final_S, final_Q = qr_algorithm_fixed_iterations(S,100)
#np.set_printoptions(precision=10, suppress=True)
print(final_S)
print(final_Q)

[[  0.           -12.3220142356  -0.0000000001   0.
   -0.            -0.             0.            -0.
    0.          ]
 [-12.3220142356  -0.            -0.            -0.
   -0.            -0.             0.            -0.
    0.          ]
 [ -0.0000000001  -0.             0.             6.4196525199
   -0.             0.            -0.            -0.
   -0.          ]
 [ -0.            -0.             6.4196525199  -0.
   -0.            -0.            -0.            -0.
   -0.          ]
 [ -0.            -0.             0.             0.
   -0.            -1.9179778279  -0.            -0.
    0.          ]
 [ -0.            -0.             0.             0.
   -1.9179778279   0.            -0.            -0.
    0.          ]
 [  0.            -0.             0.             0.
   -0.             0.            -0.             0.5266761362
    0.          ]
 [ -0.             0.            -0.            -0.
    0.            -0.             0.5266761362   0.
   -0.          ]
 [  

In [85]:
import numpy as np
import pandas as pd
MatrixA = np.array([[5,5,0,4],[1,1,5,0],[3,2,0,4],[5,3,0,5],[0,0,4,0]])
#print matrix A and rank(A)
print('A = \n',MatrixA)
print('Matrix A rank(A) = ',np.linalg.matrix_rank(MatrixA))

# calculate SVD
U, S , Vt = np.linalg.svd(MatrixA, full_matrices= False)
#print U,V^T,Sigma
print('U = \n', np.around(U,2))
print('V^T = \n', np.around(Vt,2))
print('Sigma = ', np.around(S,2))

A = 
 [[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]
Matrix A rank(A) =  4
U = 
 [[-0.65 -0.04 -0.71  0.23]
 [-0.11  0.78 -0.14 -0.24]
 [-0.43 -0.06  0.51  0.63]
 [-0.62 -0.07  0.41 -0.64]
 [-0.02  0.62  0.22  0.31]]
V^T = 
 [[-0.63 -0.49 -0.05 -0.6 ]
 [ 0.01  0.04  0.99 -0.12]
 [-0.05 -0.75  0.11  0.66]
 [-0.78  0.45  0.04  0.44]]
Sigma =  [12.32  6.42  1.92  0.53]
