# Question 1

## Question 1.a

In [1]:
import numpy as np
import pandas as pd
MatrixA = np.array([[5,5,0,4],[1,1,5,0],[3,2,0,4],[5,3,0,5],[0,0,4,0]])
#print matrix A and rank(A)
print('A = \n',MatrixA)
print('Matrix A rank(A) = ',np.linalg.matrix_rank(MatrixA))

# calculate SVD
U, S , Vt = np.linalg.svd(MatrixA, full_matrices= False)
#print U,V^T,Sigma
print('U = \n', np.around(U,2))
print('V^T = \n', np.around(Vt,2))
print('Sigma = ', np.around(S,2))

A = 
 [[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]
Matrix A rank(A) =  4
U = 
 [[-0.65 -0.04 -0.71  0.23]
 [-0.11  0.78 -0.14 -0.24]
 [-0.43 -0.06  0.51  0.63]
 [-0.62 -0.07  0.41 -0.64]
 [-0.02  0.62  0.22  0.31]]
V^T = 
 [[-0.63 -0.49 -0.05 -0.6 ]
 [ 0.01  0.04  0.99 -0.12]
 [-0.05 -0.75  0.11  0.66]
 [-0.78  0.45  0.04  0.44]]
Sigma =  [12.32  6.42  1.92  0.53]


## Question 1.b

In [3]:
import numpy as np
import pandas as pd
MatrixA = np.array([[5,5,0,4],[1,1,5,0],[3,2,0,4],[5,3,0,5],[0,0,4,0]])
#print matrix A and rank(A)
print('A = \n',MatrixA)
print('Matrix A rank(A) = ',np.linalg.matrix_rank(MatrixA))

# calculate SVD
U, S , Vt = np.linalg.svd(MatrixA, full_matrices= False)
Sigma_matrix = np.diag(S)

sigma_1_u_1 = Sigma_matrix[0,0] *  (- U[:,0])
sigma_2_u_2 = Sigma_matrix[1,1] *  (- U[:,1])
sigma_3_u_3 = Sigma_matrix[2,2] *  ( U[:,2])
sigma_4_u_4 = Sigma_matrix[3,3] *  ( U[:,3])

print('Av_1 = sigma_1_u_1 = \n',sigma_1_u_1)
print('Av_2 = sigma_2_u_2 = \n',sigma_2_u_2)
print('Av_3 = sigma_3_u_3 = \n',sigma_3_u_3)
print('Av_4 = sigma_4_u_4 = \n',sigma_4_u_4)

A = 
 [[5 5 0 4]
 [1 1 5 0]
 [3 2 0 4]
 [5 3 0 5]
 [0 0 4 0]]
Matrix A rank(A) =  4
Av_1 = sigma_1_u_1 = 
 [8.0041244  1.37300843 5.27090348 7.61955262 0.20216268]
Av_2 = sigma_2_u_2 = 
 [ 0.26629295 -5.00294986  0.38727368  0.45917319 -3.96871495]
Av_3 = sigma_3_u_3 = 
 [-1.35973748 -0.26303734  0.97916054  0.78709136  0.4269615 ]
Av_4 = sigma_4_u_4 = 
 [ 0.11914149 -0.12709031  0.32990945 -0.33476123  0.16166565]
